Handle Single Purpose Keys
iovation/launchkey-python pull request #110
Opened 2020-11-06 03:04 UTC by CMoncur

2020-11-06 21:04 UTC, lordkyzr approved these changes

2020-11-06 21:37 UTC, CMoncur commented on launchkey/clients/base.py
> +                               active=None, key_type=None):
The raw response from the API is an integer, but I definitely agree that there would be value in making an enum, especially since we can leverage that in Admin Center. I think it would be worth making a follow up ticket for that, unless you think it should go out right now with an RC?

2020-11-06 22:18 UTC, bporter125 commented on launchkey/clients/base.py
> +                               active=None, key_type=None):
The issue I see is if it isn't updated now you're signing up to have to update Admin Center in the interim of the change being made and the actual SDK release as it will straight up be a BC break and we don't want to have Admin Center randomly break when it inevitably has the SDK updated for other reasons.

2020-11-06 22:20 UTC, bporter125 commented on features/directory_client/services/public_keys/directory-client-service-public-keys-add.feature
> +    Then the Public Key is in the list of Public Keys for the Directory Service and has a "0" key type
Wouldn't this step be: `Then the Public Key is in the list of Public Keys for the Directory Service and has a "0" key type`? Based on the steps above that includes a variable there are no quotes. Are they auto adding the quotes in?

2020-11-06 22:24 UTC, bporter125 commented on launchkey/entities/validation.py
> +    key_type = validators.OneOf([0, 1, 2], if_missing=0, if_empty=0)
We generally don't want to hard validate input from API in the SDKs as that would mean that if API was to add a new type the SDK would blow up. That's why most of the validators above are just verifying the value is a datatype.

2020-11-06 22:25 UTC, bporter125 requested changes
The big issues I'm seeing is regarding the API response validator.

2020-11-06 23:09 UTC, CMoncur commented on features/directory_client/services/public_keys/directory-client-service-public-keys-add.feature
> +    Then the Public Key is in the list of Public Keys for the Directory Service and has a "0" key type
I declared two `then`s in the step implementation. One with quotes and one without. That way I can use the same verbage as the step in the Scenario Outline, and both will work.

2020-11-06 23:54 UTC, jnpblrdrgz approved these changes

2020-11-07 00:59 UTC, CMoncur commented on launchkey/entities/validation.py
> +    key_type = validators.OneOf([0, 1, 2], if_missing=0, if_empty=0)
This has been addressed in the most recent commit 👍

2020-11-07 00:59 UTC, CMoncur commented
> The big issues I'm seeing is regarding the API response validator.

Updated! 👍

2020-11-07 01:03 UTC, lordkyzr commented on launchkey/clients/base.py
> +                               active=None, key_type=None):
Yeah I personally think the enum is the way to go because you don't want client having to remember or know what the integer value is under the hood. I also agree with Brad we would have to do it now if we want to do it.

2020-11-07 01:03 UTC, bporter125 approved these changes

2020-11-07 01:04 UTC, CMoncur commented on launchkey/clients/base.py
> +                               active=None, key_type=None):
Leveraging an enum with the SDK would ensure that the SDK needs to be updated every time the API expands on the key types. Similarly to what you posted below about the validator, it seems prudent to ensure that the validator can handle an expanded range in the future. This isn't possible when leveraging an enum. What are your thoughts?

2020-11-12 23:56 UTC, CMoncur commented on launchkey/clients/base.py
> +                               active=None, key_type=None):
I've updated the PR to include and leverage the enum we discussed!

2020-11-13 00:26 UTC, jnpblrdrgz commented on features/org_client/directories/public_keys/org-client-directory-public-keys-add.feature
> +  Scenario Outline: I may add a Public Key with a key type to a Directory
Personally I find this language for the scenario confusing. Maybe "A Public Key with a key type to a Directory is present when added."

2020-11-13 00:27 UTC, bporter125 commented on launchkey/entities/shared.py
> +    other = -1
All of our other enums use all caps for the enum keys (check service/__init__.py).

2020-11-13 00:35 UTC, lordkyzr approved these changes
I really like this with the enum. It came out nice.

2020-11-13 00:40 UTC, jnpblrdrgz approved these changes

2020-11-13 00:54 UTC, CMoncur commented on launchkey/entities/shared.py
> +    other = -1
Updated! We'll have to revisit the KeyType enum in API as well.

2020-11-13 00:54 UTC, CMoncur commented on features/org_client/directories/public_keys/org-client-directory-public-keys-add.feature
> +  Scenario Outline: I may add a Public Key with a key type to a Directory
Updated!

2020-11-13 00:56 UTC, lordkyzr approved these changes

2020-11-13 23:06 UTC, merged