Update Repo Branding for Python Service SDK
iovation/launchkey-python pull request #112
Opened 2020-12-09 19:29 UTC by j7an

2020-12-09 19:47 UTC, CMoncur approved these changes
:shipit:

2020-12-09 19:49 UTC, lordkyzr commented on README.rst
> +Use to more easily interact with iovation's TruValidate Multifactor Authentication API.
I think iovation has to change to TransUnion here right?

2020-12-09 19:49 UTC, lordkyzr commented on README.rst
>  ***********************
Don't these have to be the same length as the text above?

2020-12-09 20:01 UTC, jnpblrdrgz approved these changes
I approve with Branden's comments

2020-12-10 07:41 UTC, j7an commented on README.rst
> +Use to more easily interact with iovation's TruValidate Multifactor Authentication API.
Fixed

2020-12-10 07:41 UTC, j7an commented on README.rst
>  ***********************
Fixed

2020-12-10 21:42 UTC, lordkyzr approved these changes

2020-12-10 23:31 UTC, bporter125 requested changes

2020-12-10 23:31 UTC, bporter125 commented on examples/flask-webhooks-example/README.rst
> +Example webapp to demonstrate TruValidate Multifactor Authentication webhooks using
I'm inclined to just remove the product name here. In this concept they are just webhooks as opposed to some sort of proprietary concept.

So just: `Example webapp to demonstrate webhooks using`

2020-12-10 23:31 UTC, bporter125 commented on examples/flask-webhooks-example/README.rst
> +For more information on TruValidate Multifactor Authentication webhooks see:
Same here, the product name can be removed.

2020-12-11 01:01 UTC, j7an commented on examples/flask-webhooks-example/README.rst
> +Example webapp to demonstrate TruValidate Multifactor Authentication webhooks using
fixed

2020-12-11 01:01 UTC, j7an commented on examples/flask-webhooks-example/README.rst
> +For more information on TruValidate Multifactor Authentication webhooks see:
fixed

2020-12-11 19:17 UTC, bporter125 approved these changes

2020-12-15 05:53 UTC, merged