Add Single Purpose Key Tests
iovation/launchkey-python pull request #150
Opened 2021-11-12 22:15 UTC by CMoncur

Co-authored-by: Juan Rodriguez <juanp.rodriguez@gmail.com>

2021-11-12 22:22 UTC, jnpblrdrgz approved these changes

2021-11-12 22:24 UTC, bporter125 requested changes

2021-11-12 22:24 UTC, bporter125 commented on features/base_environment.py
>      context.organization_factory.add_encryption_private_key(
This line isn't needed. It's already bein added in the constructor.

2021-11-12 22:24 UTC, bporter125 commented on features/steps/key_steps.py
> +    organization_factory.add_encryption_private_key(context.organization_encryption_private_key)
This line shouldn't be necessary.

2021-11-12 22:24 UTC, bporter125 commented on features/steps/key_steps.py
> +@when("I perform an API call using single purpose keys")
The when that doesn't have an attempt will need to not be wrapped in a try except as we want the error to be raised.

2021-11-12 22:24 UTC, bporter125 commented on features/steps/key_steps.py
> +    context.execute_steps("Then a ValueError error occurs")
This might change based on what Adam was saying in standup today but we'll see what him and Jay come up with or if it's worth it to make a more accurate error.

2021-11-12 22:26 UTC, CMoncur commented on features/steps/key_steps.py
> +    context.execute_steps("Then a ValueError error occurs")
If it is decided that this needs to be updated, then @jnpblrdrgz will be able to handle it next week while I'm on PTO! 🌴

2021-11-12 22:27 UTC, CMoncur commented on features/steps/key_steps.py
> +@when("I perform an API call using single purpose keys")
Wouldn't that make the following step a bit extraneous? There would be no point in capturing the error to verify in the "Then there are no errors" step.

2021-11-12 22:32 UTC, bporter125 commented on features/steps/key_steps.py
> +@when("I perform an API call using single purpose keys")
The try except wrap is important for `@when("I attempt an API call using single purpose keys")`, not `@when("I perform an API call using single purpose keys")`. When we aren't attempting we want it to blow up instead of catching exceptions.

2021-11-12 22:48 UTC, bporter125 approved these changes

2021-11-12 23:16 UTC, jnpblrdrgz commented on features/steps/key_steps.py
> +    context.execute_steps("Then a ValueError error occurs")
Yes I can def change it next week

2021-11-15 22:50 UTC, lordkyzr commented on features/steps/key_steps.py
> +    context.single_purpose_key_organization_factory = organization_factory
I feel like there is danger in leaving this on the context in a corrupt state and it should be cleaned up with an after_scenario tag.

2021-11-15 22:50 UTC, lordkyzr commented on features/steps/key_steps.py
> +    context.single_purpose_key_organization_factory = organization_factory
Same with this one.

2021-11-15 22:50 UTC, lordkyzr commented on features/steps/key_steps.py
> +    context.execute_steps("Then a ValueError error occurs")
This was decided to be fixed in a subsequent PR from my understanding as it is adding functionality not currently present in the SDK so I am going to resolve this conversation.

2021-11-16 21:30 UTC, lordkyzr approved these changes

2021-11-16 23:49 UTC, merged